# Generated by Django 5.2 on 2025-08-12 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cahiers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('prix', models.IntegerField()),
                ('quantite_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecoles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('adresse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-annee_debut'],
                'unique_together': {('annee_debut', 'annee_fin')},
            },
        ),
        migrations.CreateModel(
            name='BilanAnneeScolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_ventes_total', models.IntegerField(default=0)),
                ('montant_total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_total_impaye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventes_par_cahier', models.JSONField(default=dict)),
                ('nombre_ecoles_actives', models.IntegerField(default=0)),
                ('date_generation', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='gestion.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_paiement', models.DateTimeField(null=True)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='gestion.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='gestion.ecoles')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('numero_tranche', models.IntegerField(default=1)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.vente')),
            ],
            options={
                'ordering': ['numero_tranche'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('montant', models.IntegerField()),
                ('cahier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cahiers')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.vente')),
            ],
        ),
        migrations.CreateModel(
            name='BilanMensuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('nombre_ventes', models.IntegerField(default=0)),
                ('montant_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ventes_par_cahier', models.JSONField(default=dict)),
                ('date_generation', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_mensuels', to='gestion.anneescolaire')),
            ],
            options={
                'ordering': ['annee', 'mois'],
                'unique_together': {('annee_scolaire', 'mois', 'annee')},
            },
        ),
    ]
