# Generated by Django 5.2 on 2025-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='articles_ajoutes_session',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='derniere_modification_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
