# Generated by Django 5.2 on 2025-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_vente_articles_ajoutes_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='description_dette',
            field=models.TextField(blank=True, help_text="Description de la dette (ex: 'Reliquat année 2023-2024')", null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='dette_precedente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dette des années précédentes', max_digits=10),
        ),
    ]
