# Generated by Django 5.2 on 2025-08-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_vente_description_dette_vente_dette_precedente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignevente',
            options={'ordering': ['date_ajout']},
        ),
        migrations.AddField(
            model_name='lignevente',
            name='date_ajout',
            field=models.DateTimeField(blank=True, help_text="Date et heure d'ajout de cette ligne à la vente", null=True),
        ),
        migrations.AlterField(
            model_name='cahiers',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
