# Generated by Django 5.2 on 2025-08-23 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_lignevente_options_lignevente_date_ajout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date et heure d'ajout de cette ligne à la vente"),
            preserve_default=False,
        ),
    ]
