# Generated by Django 5.2 on 2025-08-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_lignevente_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='dette_precedente',
        ),
    ]
