# Generated by Django 5.2 on 2025-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_vente_dette_precedente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoles',
            name='representant',
            field=models.TextField(blank=True, default=''),
        ),
    ]
