# Generated by Django 5.2 on 2025-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_emailnotification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='est_annule',
            field=models.BooleanField(default=False),
        ),
    ]
